# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  relase:
    cmds:
      - awk -v ver="$(cat VERSION)" 'BEGIN{FS=OFS="\""} /version\s*=/ {$2=ver} 1' setup.py > setup.py.tmp && mv setup.py.tmp setup.py
      - git push --tags
