# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  release:
    cmds:
      - awk -v ver="$(cat VERSION)" 'BEGIN{FS=OFS="\""} /version\s*=/ {$2=ver} 1' pyproject.toml> pyproject.toml.tmp && mv pyproject.toml.tmp pyproject.toml
      - git add .
      - git commit -m "bumped version for new release"
      - git push
      - git push --tags
