# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  release:
    cmds:
      - awk -v ver="$(cat VERSION)" 'BEGIN{FS=OFS="\""} /version\s*=/ {$2=ver} 1' setup.py.bak > setup.py.bak.tmp && mv setup.py.bak.tmp setup.py.bak
      - git push --tags
