# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  release:
    cmds:
      - git add .
      - git commit -m "bumped version for new release"
      - git push
      - git push --tags
