name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Git tags and version
        run: |
          git tag -l 'v*'  # List visible tags—check if the current one (e.g., v0.15.3) appears
          git describe --tags --always  # Show what Git sees for the current commit
          python -m pip install setuptools-scm  # Temp install for debug (remove later)
          python -c "from setuptools_scm import get_version; print('Detected version:', get_version())" 

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
